name: instagram_feed_clone
description: Instagram Pixel-Perfect Feed - Flutter UI/UX Challenge
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
